eureka:
  server:
    renewal-percent-threshold: 0.49
  client:
    #registerWithEureka: false
    #fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
    register-with-eureka: false
    fetch-registry: false

